template_path: templates/subnets.py
protect: False
parameters:
  VpcId:
    !stack_output vpc::VpcId
  IgwId:
    !stack_output vpc::IgwId
  StackPrefix: {{ var.stack_prefix }}
  PubSubnet1CidrBlock: 10.0.1.0/24
  PrivSubnet1CidrBlock: 10.0.11.0/24
dependencies:
  - prod/ew2/vpc
