template_path: templates/vpn.py
hooks:
  before_create:
    - !start_vpn_instance {{ var.stack_prefix }}-openvpn
  before_update:
    - !start_vpn_instance {{ var.stack_prefix }}-openvpn
parameters:
  KeyName: {{ var.keypair }}
  VpcId:
    !stack_output vpc::VpcId
  PublicSubnetId:
    !stack_output subnets::PubSubnet1Id
  AccessIP: !find_my_ip
  StackPrefix: {{ var.stack_prefix }}
sceptre_user_data:
  enable_ssh: false
dependencies:
  - prod/ew2/subnets
