template_path: templates/vpn.py
parameters:
  AmiId: {{ var.ami_id }}
  KeyName: {{ var.keypair }}
  VpcId:
    !stack_output vpc::VpcId
  PublicSubnetId:
    !stack_output subnets::PubSubnet1Id
  SSHIP: !find_my_ip
  StackPrefix: {{ var.stack_prefix }}
sceptre_user_data:
  enable_ssh: false
