service: lambdas

provider:
  name: aws
  profile: <YOUR_PROFILE>
  runtime: python2.7
  region: eu-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:DescribeInstances"
        - "ec2:StopInstances"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - route53:ChangeResourceRecordSets
      Resource: "*"

functions:
  stop_vpn:
    handler: stop_vpn.main
    events:
     - schedule: cron(0 01 * * ? *)
  update_r53:
    handler: update_r53.main
    environment:
      HOSTED_ZONE_ID: <YOUR_HOSTED_ZONE_ID>
      RECORDSET: <FDQN>
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ec2"
            detail-type:
              - "EC2 Instance State-change Notification"
            detail:
              instance-id:
                - <INSTANCE_ID_TO_GET_EVENT>
              state:
                - running
          enabled: true
